  task-runners-main:
    build:
      context: ./runners
    image: n8n-runners-custom:latest
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      - N8N_RUNNERS_MAX_CONCURRENCY=5
      - N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT=300
